### ISSUE TITLE
Port Projecttype to netstandard

### ISSUE THREAD

**Issue by mfe-** [mfe-/Prism.Validation#1]
See for ref. https://oren.codes/2016/06/23/portable-is-dead-long-live-netstandard/

**Comment by mfe-** [comment]
Blocked by https://github.com/PrismLibrary/Prism/issues/683

**Comment by weitzhandler** [comment]
Voting too.

**Comment by mfe-** [comment]
I changed the Prism.Validation PCL to .Net Standard 1.4 by using `"imports": "portable45-net45+win8+wp8+wpa81"` in the project.json file.

I don't know if this workaround is acceptable, because it seems not very user friendly.

Currently a user which wants to use the nuget package Prism.Validation has to do the following steps:

1. Create a PCL which targets .Net Standard 1.4
2. Make sure your NETStandard.Libary is up to date
3. Open project.json and replace 
```
  "frameworks": {
    "netstandard1.4": { }
  }
```
with
 ```
  "frameworks": {
    "netstandard1.4": {
      "imports": "portable45-net45+win8+wp8+wpa81"
    }
  }
```
4. Install Nuget Package Prism.Validation
5. Make sure your WPF Project uses at least .Net Framework 4.6.1
6. Install Nuget Package Prism.Validation
7. Reference the PCL Project in the WPF Project

I'm not sure if I should publish the current version as nuget package.
