### ISSUE TITLE
Supports Async ?

### ISSUE THREAD

**Issue by GreatFireWall** [mfe-/Prism.Validation#17]

**Comment by mfe-** [comment]
what?

**Comment by GreatFireWall** [comment]
Does this library supports async validation ?

**Comment by mfe-** [comment]
The validation is based on the `System.ComponentModel.DataAnnotations` by annotating Attributes to your Model btw. ViewModel. The current implementation doesn't execute the validation asynchronously. PR`s are welcome.

**Comment by GreatFireWall** [comment]
Understood, thanks. :)

**Comment by mfe-** [comment]
Feel free to reopen for any further questions.
